possible fix for non-functional backspace key
grembo/pftop pull request #1
Opened 2022-06-06 17:31 UTC by luckman212

this fixes the <kbd>BACKSPACE</kbd> not working for me in pfSense / pfTop

2022-06-06 17:32 UTC, luckman212 commented
related thread:  https://forum.netgate.com/topic/172645/pftop-bugs-rnr-does-not-work-states-shown-as-or-0

2022-06-07 08:48 UTC, grembo commented
@luckman212 When using pftop on a FreeBSD client, it works as expected. That's because it sends ^H as backspace.

When using macOS I see the behavior you're describing. You can change it easily by changing Terminal's configuration for the profile you're using:

```
Preferences -> Profiles -> (Select your profile) -> Advanced -> [x] Delete sends Control-H
```

If you're using iTerm2, you can enable Ctrl-H like below:

```
iTerm2 -> Preferences -> Keys -> Key Mappings -> click on the + symbol -> Click to Set -> press backspace -> select 'Send ^H Backspace'
```

Doing this has the advantage of fixing all kind of utilities that might have the same issue.

I'll also look into patching pftop, but I need to do some research first.

2022-06-07 09:38 UTC, grembo requested changes

2022-06-07 09:38 UTC, grembo commented on engine.c
> +	case 0x7f:
```suggestion
	case KEY_BACKSPACE:
	case 0x7f:
```

Can you put `case KEY_BACKSPACE` back above this line, so both, KEY_BACKSPACE and 0x7f are in there?

2022-06-07 13:39 UTC, luckman212 commented
Thanks @grembo for the help here. I really appreciate the iTerm2 tip. I tried that and confirm that it also works. But I imagine most people won't have this set since it's a non-defalt setting and requires diving into advanced prefs. This small patch seems like it wouldn't hurt.

2022-06-07 16:20 UTC, merged

2022-06-07 16:31 UTC, grembo commented
@luckman212 Thanks for your contribution.

[I updated the `sysutils/pftop`](https://cgit.freebsd.org/ports/commit/?id=6bf98721cfbbc4e45ea1d6058ec33e010e1663cd), which means a binary package will be available on the official FreeBSD repos soon (few days max) to those using the `latest` repo.

In case you're using the `quarterly` repo, your change will be part of the 2022Q3 package set, which will become available in early July.